### ISSUE TITLE
感谢您提供的公式识别项目

### ISSUE THREAD

**Issue by ilove404** [hahamyt/hahamyt.github.io#1]
非常感谢您提供的公式识别项目，为我的学习和科研工作带来了非常大的便捷。您是否能提供一个打赏路径呢，我将非常乐意为您的工作付费。

**Comment by hahamyt** [comment]
非常感谢！受到你的认可真的很开心，目前网站还不够好用，还不足以接受打赏，后续会慢慢完善变得更有用，再次感谢~~
